### ISSUE TITLE
Custom Functions template generated from generator-office is giving #BUSY! error

### ISSUE THREAD

**Issue by zakhan4** [OfficeDev/generator-office#449]
My Office Version
![office version](https://user-images.githubusercontent.com/41992420/57458333-73222800-7271-11e9-80fe-614752bbbe87.PNG)
My generator-office version: 1.2.3

I generated the latest template project for Custom Functions using generator-office. Then I tried to run the project following the instructions. It sideloaded successfully along with the custom functions installed. But when I tried to execute any formula, it shows #BUSY! error with "We're starting the add-ins runtime, just a moment..." showing in the below status bar indefinitely as shown in the attached image below.

![Capture](https://user-images.githubusercontent.com/41992420/57458349-76b5af00-7271-11e9-86d3-97b119f74c2b.PNG)

**Comment by akrantz** [comment]
Use `npx office-addin-dev-settings runtime-log --enable` and open the log file. I recommend using VS Code because it load changes as the log file is changed. You can then close Excel, and relaunch. The log file should then hopefully have more information.

**Comment by zakhan4** [comment]
[OfficeAddins.log.txt](https://github.com/OfficeDev/generator-office/files/3162532/OfficeAddins.log.txt)

I tried it, but it wasn't much help in identifying the issue. The log just stucked at "Verbose	CustomFunctions	[Execution] [Async] [Begin] Function=CONTOSO.ADD, Workbook=excel add-in d4a97ccd-788b-4ed1-9213-1d871a4d2862.xlsx"  after executing the CONTOSO.add(1,2) formula

**Comment by akrantz** [comment]
The log shows manifest errors for a different add-in. You should try unloading that add-in.

I would also make sure to close all instances of excel, and then remove the "Wef" folder in %LocalAppData%\Microsoft\Office\16.0\Wef. Then try again.

**Comment by zakhan4** [comment]
I already did removed %LocalAppData%\Microsoft\Office\16.0\Wef folder and restarted excel. But it did not make any difference. Can you guide me as to how I can unload all the other add-ins?

**Comment by akrantz** [comment]
Use `npx office-toolbox remove` to remove any add-ins registered for development. These appear in the My Add-ins button drop-down list in Excel (on the Insert tab). You might also have installed an add-in via the File Options, Trust Center, Trust Center Settings..., Trusted Add-in Catalogs. If so, you can remove them there.  

I would also then clear the OfficeAddins.log.txt log file and save it so you can see what new items are written on the next launch.

When you run "npm start" or use VS Code launch configs, this will register the add-in for development, and then sideload the add-in.

**Comment by keyur32** [comment]
Hi, this is a known issue currently on that build for Office Insiders in the 1906 build. You can change your channel to monthly channel and it will work or use the 64 bit version of office. Team is working on a fix.

**Comment by zakhan4** [comment]
Hi, 
@keyur32 and @akrantz thanks for your responses. As @keyur32 mentioned, I tried to reinstall my Office to 64-bit and Custom Functions worked with the latest version. Should I close this issue or keep it open, as there is still a bug that needs to be fixed?

Also, I have one more question regarding the general availability of Custom Functions. Since we know that Custom functions are available after Version 1904 (Build 11601.20144) or later if you are connected to the Office 365 subscriptions now. Can we expect it to be available for Retail versions of Office 2016 C2R and Office 2019 in the future when they will get new updates?

**Comment by akrantz** [comment]
@zakhan4 I'm glad that you were able to resolve this. I think we can leave this open until the fix is available.

I'll let @keyur32 answer your other question about availability.

**Comment by keyur32** [comment]
Hi @zakhan4, the feature is available on Office 365 (1904+). It also is enabled for Office Online via  a personal Microsoft account.  
We don't have plans to backport to previous versions at this time

**Comment by zakhan4** [comment]
Thanks for the clarification. 

Just to confirm once again @keyur32 . So, even if the users get an update to version 1904+ for retail versions of Office 2019, custom functions will still not be included in that?

I saw that retail versions of Office also has the same build and version numbers as Office 365 from this link https://docs.microsoft.com/en-us/officeupdates/update-history-office-2019. That's why I got a bit confused.

**Comment by bestekov** [comment]
So just to confirm... the required version for custom functions is now 1904? The docs here: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-requirements say that the required versions are:
* Excel on Windows (64-bit version 1810 or later)
* Excel for Mac (version 13.329 or later)

What are the actual required versions for Windows and Mac?

I had just had my O365 administrators change me to the Semi-Annual (targeted) channel (currently on 1902) assuming that this would all start working. But it sounds like it will only run on Monthly?

The issue I am seeing is after doing a clean install of the function template and running `npm start` excel (desktop windows) starts but displays an error message `This add-in is no longer available` , which I assume is the same as the original problem reported in this issue?

**Comment by zakhan4** [comment]
Hi @bestekov,

I think the page here: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-requirements is outdated. 

For custom functions required version now look at this link: https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets#custom-functions. Hope it helps.

**Comment by zakhan4** [comment]
@akrantz unfortunately I'm still facing this issue with the 64-bit version of Office as well. And also one of my colleagues is using monthly channel and they are facing the same issue. 

I'm sorry to say that it has resolved before. The way that it worked for me and I thought that the issue is resolved is when I use 'npm run build' command to generate the production build and then deploy it on a server and then used it. That way it worked. But when I still run for development using 'npm start', I'm getting the same error again. 

There is only one change that I made to the template in the manifest file which is this: 
`<bt:Url id="Functions.Script.Url" DefaultValue="https://localhost:3000/functions.js"/>
<bt:Url id="Functions.Metadata.Url" DefaultValue="https://localhost:3000/functions.json"/>
<bt:Url id="Functions.Page.Url" DefaultValue="https://localhost:3000/functions.html"/>`

Because there were no js and html files available inside 'dist' folder, when I ran the web server and I could not even install the Custom functions without making this change. 

You can find the logs in this file: 
[OfficeAddins.log.txt](https://github.com/OfficeDev/generator-office/files/3182471/OfficeAddins.log.txt)

My Office version now: 
![image](https://user-images.githubusercontent.com/41992420/57774863-f3d29f80-771b-11e9-8f34-5dd94e9dd89c.png)

**Comment by akrantz** [comment]
You need to use `npm run build` (prod) or `npm run build-dev` before `npm start`. Perhaps the documentation is not clear.

If you're using VS Code, then I recommend opening the folder in VS Code, then using Terminal, Run Task, `Dev Server` and then Terminal, Run Task, `Watch`. Then you can start debugging from the Debug view (Excel Desktop launch config).

**Comment by zakhan4** [comment]
@akrantz thanks for your response. It seems to work this way. 

I have one question though. Is remote debugging option from VS Code is only available for custom functions, and not for taskpane and add-in commands right now? 

And if that is the case, in the future will it be possible to debug taskpane and add-in commands from VS Code as well?

**Comment by akrantz** [comment]
Yes, because the task pane runs using an IE WebView control, the taskpane code cannot be debugged using VS Code, since there is not a debug extension that provides this capability. The custom functions runtime uses the ChakraCore JavaScript engine (on Windows) directly, and we did work to enable debugging ChakraCore from VS Code. To debug the taskpane code, use Attach Debugger to debug using Visual Studio, or you can use Ithe F12 DevTools. Add-in commands run in a separate hidden WebView from the task pane, and because it is hidden, there is no way to use the Attach Debugger command. 

 I know this is not ideal. Our desire is to enable VS Code debugging everywhere.

One change happening is moving from the IE WebView to the Edge WebView. This is tied to the Windows 10 Version 1903 update. This doesn't actually change the capability of VS Code to debug, as both IE and Edge use the same debugging mechanism which is only supported by Visual Studio or the browser dev tools. 

However, Edge is also moving to use Chromium. We anticipate, but cannot confirm right now, that Office would potentially use the Edge Chromium WebView, which would use the V8 JavaScript engine, and be able to be debugged from VS Code. That would provide the ability to debug both the taskpane and custom functions from VS Code.

The one alternative that you can do today is to debug the taskpane and custom functions running in Excel Online using the Edge browser. I added a VS Code launch target for Edge. It is a little cumbersome as you need to copy a share url for a document, and then paste that in on F5 so that the document is loaded in a tab which can be debugged. But once you do that, both code for the taskpane and for custom functions can be debugged with VS Code. 

We would very much appreciate your feedback about this. For example, does it make a difference whether you debug your JavaScript/TypeScript code using Excel Online or Excel Desktop? Is it more or less convenient to use the browser? What can we do to make the development experience more productive?

**Comment by zakhan4** [comment]
@akrantz thanks a lot for such a clear and descriptive response. Our team would for sure try out the debugging options for Excel Online, and will update you with our feedback. 

Is there a specific place where we can submit our feedback?

**Comment by bestekov** [comment]
One data point for others following this issue...

I upgraded to Monthly channel (`1904` as of this comment) and re-built the unmodified office custom function (javascript) template. Excel now said "failed to load extension".

I then ran `npx office-addin-dev-settings runtime-log --enable` as referenced in an earlier comment on this issue to try to see *why* it failed to load, but then it just started working. I'm not sure if something about running that `office-addin-dev-settings` command made it work or if it was just running it twice that worked.

**Comment by TCourtneyOwen** [comment]
@zakhan4 Closing this issue since we haven't heard about similar problems with Custom Functions for awhile.  Please update to the latest version of yo office (1.3.0) to see if this fixes the issue. If not, please reopen the issue and we will investigate further.
